# Generated by Django 4.2.7 on 2024-03-05 14:47

import apps.flax_id.django.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Frame",
            fields=[
                (
                    "id",
                    apps.flax_id.django.fields.FlaxId(
                        editable=False, max_length=16, primary_key=True, serialize=False
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("image_data", models.BinaryField(blank=True, null=True)),
                ("segment_data", models.BinaryField(blank=True, null=True)),
                (
                    "segment_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="videos.video"
                    ),
                ),
            ],
        ),
    ]
