# Generated by Django 4.2.7 on 2024-03-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0002_frame"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
    ]
